#!/bin/bash
# Guide: Which Logs to Check for CDC Pipeline Issues

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  GUIDE: WHICH LOGS TO CHECK                               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

echo "When investigating CDC pipeline issues, check logs in this order:"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "1. KAFKA CONNECT LOGS (Most Important)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This is where connector errors, task failures, and 500 errors originate."
echo ""
echo "Commands:"
echo "  # Last 100 lines"
echo "  docker logs kafka-connect-clickhouse --tail 100"
echo ""
echo "  # Follow live (Ctrl+C to stop)"
echo "  docker logs kafka-connect-clickhouse --follow"
echo ""
echo "  # Search for errors"
echo "  docker logs kafka-connect-clickhouse 2>&1 | grep -i error | tail -20"
echo ""
echo "  # Search for specific connector"
echo "  docker logs kafka-connect-clickhouse 2>&1 | grep mysql-source-connector | tail -20"
echo ""
echo "What to look for:"
echo "  - 'OutOfMemoryError' → Memory issues"
echo "  - 'Task.*failed' → Connector task crashed"
echo "  - 'Connection refused' → Cannot reach MySQL/ClickHouse"
echo "  - 'ClickHouseException' → Data going to DLQ"
echo "  - 'snapshot.*complete' → Snapshot finished"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "2. CLICKHOUSE LOGS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check if ClickHouse is refusing connections or crashing."
echo ""
echo "Commands:"
echo "  # Last 100 lines"
echo "  docker logs clickhouse-server --tail 100"
echo ""
echo "  # Search for errors"
echo "  docker logs clickhouse-server 2>&1 | grep -i 'error\|exception' | tail -20"
echo ""
echo "  # Check ClickHouse server log file (inside container)"
echo "  docker exec clickhouse-server cat /var/log/clickhouse-server/clickhouse-server.log | tail -50"
echo ""
echo "What to look for:"
echo "  - 'Code: 1001' → Internal ClickHouse errors"
echo "  - 'Memory limit exceeded' → Out of memory"
echo "  - 'Too many parts' → Table needs optimization"
echo "  - 'Cannot parse' → Data format issues"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "3. REDPANDA LOGS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check if Redpanda (Kafka) is having issues."
echo ""
echo "Commands:"
echo "  # Last 100 lines"
echo "  docker logs redpanda-clickhouse --tail 100"
echo ""
echo "  # Check broker health"
echo "  docker exec redpanda-clickhouse rpk cluster health --brokers localhost:9092"
echo ""
echo "What to look for:"
echo "  - 'Broker not available' → Redpanda crashed"
echo "  - 'Topic.*error' → Topic access issues"
echo "  - 'Out of disk space' → Storage full"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "4. DOCKER CONTAINER STATUS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check if containers are running and healthy."
echo ""
echo "Commands:"
echo "  # Check all containers"
echo "  docker ps -a | grep -E 'kafka-connect|clickhouse|redpanda'"
echo ""
echo "  # Check resource usage"
echo "  docker stats --no-stream kafka-connect-clickhouse clickhouse-server redpanda-clickhouse"
echo ""
echo "  # Check container restarts"
echo "  docker ps -a --filter 'name=kafka-connect' --format 'table {{.Names}}\t{{.Status}}'"
echo ""
echo "What to look for:"
echo "  - 'Exited' status → Container crashed"
echo "  - 'Restarting' → Container in crash loop"
echo "  - High memory % → Out of memory soon"
echo "  - High CPU % → Processing heavy load"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "5. SYSTEM LOGS (Host Machine)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check if host system has issues."
echo ""
echo "Commands:"
echo "  # Check disk space"
echo "  df -h"
echo ""
echo "  # Check memory usage"
echo "  free -h"
echo ""
echo "  # Check docker logs"
echo "  sudo journalctl -u docker --since '10 minutes ago' | tail -50"
echo ""
echo "What to look for:"
echo "  - Disk usage > 90% → Out of space"
echo "  - Memory usage > 95% → Out of memory"
echo "  - 'OOM killed' → Process killed by OS"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "COMMON ERROR PATTERNS AND SOLUTIONS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Problem: 500 errors in Redpanda console"
echo "  Cause: Kafka Connect is down or crashed"
echo "  Check: docker ps | grep kafka-connect"
echo "  Fix: docker restart kafka-connect-clickhouse"
echo ""
echo "Problem: Connectors show FAILED"
echo "  Cause: Configuration error or dependency unavailable"
echo "  Check: curl http://localhost:8085/connectors/[name]/status | jq"
echo "  Fix: Check logs, fix config, redeploy connector"
echo ""
echo "Problem: Data not flowing to ClickHouse"
echo "  Cause: Connector stopped, DLQ filling up, or consumer lag"
echo "  Check: rpk group describe connect-clickhouse-sink-connector"
echo "  Fix: Check connector status, investigate DLQ errors"
echo ""
echo "Problem: OutOfMemoryError in logs"
echo "  Cause: Kafka Connect heap size too small"
echo "  Check: docker logs kafka-connect-clickhouse | grep OutOfMemory"
echo "  Fix: Increase KAFKA_HEAP_OPTS in docker-compose.yml"
echo ""
echo "Problem: Snapshot never completes"
echo "  Cause: MySQL slow, network issues, or connector crashed"
echo "  Check: docker logs kafka-connect-clickhouse | grep snapshot"
echo "  Fix: Check MySQL connectivity, restart connector"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "QUICK DIAGNOSTIC SCRIPTS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run these scripts for quick diagnostics:"
echo ""
echo "  ./check_connector_health.sh"
echo "    - Checks connector status"
echo "    - Shows if snapshot is complete"
echo "    - Displays consumer lag"
echo "    - Shows recent errors"
echo ""
echo "  ./analyze_connector_logs.sh"
echo "    - Analyzes last 1000 log lines"
echo "    - Categorizes errors by type"
echo "    - Provides specific solutions"
echo "    - Shows error counts"
echo ""
echo "  ./quick_status_check.sh"
echo "    - Quick overview of pipeline health"
echo "    - Data sync progress"
echo "    - DLQ status"
echo "    - ETA for completion"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
