CREATE TABLE IF NOT EXISTS analytics.`casino_setting`
(
    `id` Int64,
    `stake_tax1_label` String DEFAULT '',
    `stake_tax1` Decimal(20,8),
    `stake_tax2_label` String DEFAULT '',
    `stake_tax2` Decimal(20,8),
    `stake_tax3_label` String DEFAULT '',
    `stake_tax3` Decimal(20,8),
    `withdrawal_tax1_label` String DEFAULT '',
    `withdrawal_tax1` Decimal(20,8),
    `withdrawal_tax2_label` String DEFAULT '',
    `withdrawal_tax2` Decimal(20,8),
    `withdrawal_tax3_label` String DEFAULT '',
    `withdrawal_tax3` Decimal(20,8),
    `default_country_code` Int32,
    `default_currency` String,
    `default_language_code` String,
    `content_server_host` String DEFAULT '',
    `content_server_username` String DEFAULT '',
    `content_server_password` String DEFAULT '',
    `spribe_launcher_host` String DEFAULT '',
    `spribe_operator_id` Int32 DEFAULT 0,
    `spribe_default_language` String DEFAULT '',
    `kiron_virtual_launcher_base_url` String DEFAULT '',
    `kiron_virtual_operator_id` Int32 DEFAULT 0,
    `split_the_pot_launcher_base_url` String DEFAULT '',
    `split_the_pot_operator_id` Int32 DEFAULT 0,
    `split_the_pot_api_key` String DEFAULT '',
    `split_the_pot_losing_bet_notification` Bool,
    `qtech_pass_key` String DEFAULT '',
    `qtech_url` String DEFAULT '',
    `qtech_api_user` String DEFAULT '',
    `qtech_api_password` String DEFAULT '',
    `qtech_default_language` String DEFAULT '',
    `qtech_return_url` String DEFAULT '',
    `smart_soft_launcher_base_url` String DEFAULT '',
    `smart_soft_return_url` String DEFAULT '',
    `smart_soft_signature_key` String DEFAULT '',
    `smart_soft_portal_name` String DEFAULT '',
    `kiron_lite_launcher_base_url` String DEFAULT '',
    `kiron_lite_app_key` String DEFAULT '',
    `kiron_lite_api_key` String DEFAULT '',
    `kiron_lite_project_code` String DEFAULT '',
    `golden_race_launcher_base_url` String DEFAULT '',
    `golden_race_private_key` String DEFAULT '',
    `shack_evolution_url` String DEFAULT '',
    `shack_evolution_client_id` Int32 DEFAULT 0,
    `shack_evolution_email` String DEFAULT '',
    `shack_evolution_public_key` String DEFAULT '',
    `atlas_base_url` String DEFAULT '',
    `atlas_casino_id` Int32 DEFAULT 0,
    `atlas_private_key` String DEFAULT '',
    `booming_api_key` String DEFAULT '',
    `booming_api_secret` String DEFAULT '',
    `booming_base_url` String DEFAULT '',
    `aviatrix_base_url` String DEFAULT '',
    `aviatrix_operator_identifier` Int32 DEFAULT 0,
    `aviatrix_operator_lobby_url` String DEFAULT '',
    `aviatrix_secret_key` String DEFAULT '',
    `spribe_ips` String DEFAULT '',
    `spribe_api_url` String DEFAULT '',
    `spribe_secret_token` String DEFAULT '',
    `heropicks_launcher_base_url` String DEFAULT '',
    `heropicks_secret` String DEFAULT '',
    `insa_instant_base_url` String DEFAULT '',
    `insa_instant_client_id` Int32 DEFAULT 0,
    `insa_instant_client_secret` String DEFAULT '',
    `insa_instant_jwt_secret_key` String DEFAULT '',
    `insa_instant_lobby_url` String DEFAULT '',
    `abracadabra_base_url` String DEFAULT '',
    `abracadabra_merchant_key` String DEFAULT '',
    `abracadabra_play_service_id` Int32 DEFAULT 0,
    `phoenix_base_url` String DEFAULT '',
    `phoenix_jwt_secret_key` String DEFAULT '',
    `phoenix_operator_id` Int32 DEFAULT 0,
    `betsoft_bank_id` Int32 DEFAULT 0,
    `betsoft_base_url` String DEFAULT '',
    `betsoft_jwt_secret_key` String DEFAULT '',
    `betsoft_secret_key` String DEFAULT '',
    `phoenix_public_key` String DEFAULT '',
    `phoenix_api_base_url` String DEFAULT '',
    `sport_bespoke_base_url` String DEFAULT '',
    `sport_bespoke_iframe_url` String DEFAULT '',
    `sport_bespoke_operator_id` Int32 DEFAULT 0,
    `sport_bespoke_secret_key` String DEFAULT '',
    `_version` UInt64 DEFAULT 0,
    `_is_deleted` UInt8 DEFAULT 0,
    `_extracted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_version, _is_deleted)
ORDER BY (`id`)
SETTINGS clean_deleted_rows = 'Always',
         index_granularity = 8192;
