CREATE TABLE IF NOT EXISTS analytics.`flatodd_member`
(
    `id` Int32,
    `user_id` Int32,
    `disabled` Bool,
    `city` LowCardinality(String) DEFAULT '',
    `kebele` LowCardinality(String) DEFAULT '',
    `location` String DEFAULT '',
    `woreda` LowCardinality(String) DEFAULT '',
    `zone` LowCardinality(String) DEFAULT '',
    `region` LowCardinality(String) DEFAULT '',
    `contact_confirmed` Bool,
    `created_at` DateTime64(6, 'UTC'),
    `sms_bulk_stopped` Bool,
    `member_type` UInt16,
    `last_bet_id` Int32 DEFAULT 0,
    `last_branch_deposit_id` Int32 DEFAULT 0,
    `last_branch_withdrawal_id` Int32 DEFAULT 0,
    `last_online_deposit_id` Int32 DEFAULT 0,
    `last_online_withdrawal_id` Int32 DEFAULT 0,
    `updated_at` DateTime64(6, 'UTC'),
    `date_of_birth` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `hashed_username` String DEFAULT '',
    `telegram_chat_id` Int32 DEFAULT 0,
    `utm_campaign_id` Int64 DEFAULT 0,
    `utm_source_id` Int64 DEFAULT 0,
    `identification_document` String DEFAULT '',
    `identification_number` Int32 DEFAULT 0,
    `identification_type` UInt16 DEFAULT 0,
    `source_of_fund` UInt16 DEFAULT 0,
    `source_of_fund_detail` String DEFAULT '',
    `country` Int32 DEFAULT 0,
    `nationality` String DEFAULT '',
    `gender` LowCardinality(String) DEFAULT '',
    `tag_id` Int32 DEFAULT 0,
    `contact_confirmed_on` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `identification_expiry_date` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `identification_issue_date` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `identification_sub_division` String DEFAULT '',
    `deposit_transaction_setting` UInt32,
    `max_daily_deposit_amount` Nullable(Decimal64(2)),
    `max_daily_deposit_number` UInt32 DEFAULT 0,
    `max_daily_wallet_received_amount` Nullable(Decimal64(2)),
    `max_daily_wallet_received_number` UInt32 DEFAULT 0,
    `max_daily_wallet_sent_amount` Nullable(Decimal64(2)),
    `max_daily_wallet_sent_number` UInt32 DEFAULT 0,
    `max_daily_withdraw_amount` Nullable(Decimal64(2)),
    `max_daily_withdraw_number` UInt32 DEFAULT 0,
    `wallet_transfer_setting` UInt32,
    `withdraw_transaction_setting` UInt32,
    `affiliate_id` Int32 DEFAULT 0,
    `affiliate_provider` UInt16 DEFAULT 0,
    `current_streak` Int32 DEFAULT 0,
    `last_activity_date` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `last_streak` Int32 DEFAULT 0,
    `longest_streak` Int32 DEFAULT 0,
    `deposit_count` UInt32,
    `casino_cool_off_duration` String DEFAULT '',
    `casino_cool_off_last_updated_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `daily_deposit_limit` Nullable(Decimal64(2)),
    `daily_deposit_limit_last_updated_at` Nullable(DateTime),
    `deposit_cool_off_duration` String DEFAULT '',
    `deposit_cool_off_last_updated_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `last_deposited_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `monthly_deposit_limit` Nullable(Decimal64(2)),
    `monthly_deposit_limit_ends_at` Nullable(Date),
    `monthly_deposit_limit_last_updated_at` Nullable(DateTime),
    `sport_cool_off_duration` String DEFAULT '',
    `sport_cool_off_last_updated_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `virtual_cool_off_duration` String DEFAULT '',
    `virtual_cool_off_last_updated_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `weekly_deposit_limit` Nullable(Decimal64(2)),
    `weekly_deposit_limit_ends_at` Nullable(Date),
    `weekly_deposit_limit_last_updated_at` Nullable(DateTime),
    `affiliate_promo_code` String DEFAULT '',
    `utm_content_id` Int64 DEFAULT 0,
    `utm_medium_id` Int64 DEFAULT 0,
    `utm_term_id` Int64 DEFAULT 0,
    `_version` UInt64 DEFAULT 0,
    `_is_deleted` UInt8 DEFAULT 0,
    `_extracted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_version, _is_deleted)
ORDER BY (`id`)
PARTITION BY toYYYYMM(`created_at`)
SETTINGS clean_deleted_rows = 'Always',
         index_granularity = 8192;
