CREATE TABLE IF NOT EXISTS analytics.`flatodd_mainconfiguration`
(
    `configuration_ptr_id` Int32,
    `maximum_pending_stake` Float64,
    `maximum_pending_slips` Int32,
    `maximum_duplicate_slips` Int32,
    `maximum_daily_withdraw` Float64,
    `withdrawal_contact_confirm` Bool,
    `transfer_contact_confirm` Bool,
    `referral_support` Bool,
    `maximum_stake` Float64,
    `minimum_deposit_amount` Decimal64(2),
    `branch_max_single_deposit_amount` Decimal64(2),
    `branch_withdrawal_enabled` Bool,
    `offline_payout_enabled` Bool,
    `system_max_duplicate_slips` Int32,
    `system_number_pick_duplicate_slips` Int32,
    `currency` String,
    `maximum_deposit_amount` Decimal64(2),
    `enable_bet_cancelled_sms` Bool,
    `enable_bet_placed_sms` Bool,
    `enable_bet_win_notification_sms` Bool,
    `enable_deposit_succeed_sms` Bool,
    `enable_password_reset_sms` Bool,
    `enable_phone_confirmation_sms` Bool,
    `enable_registeration_confirmation_sms` Bool,
    `max_win_for_win_notification` Float64 DEFAULT 0.0,
    `useridentifier_deposit_editable` Bool,
    `useridentifier_withdraw_editable` Bool,
    `offline_bet_support` Bool,
    `offline_minimum_stake` Float64,
    `offlineticket_sold_criteria` String,
    `online_minimum_stake` Float64,
    `all_balance_withdrawable` Bool,
    `minimum_withdraw_amount` Decimal64(2),
    `online_withdrawal_enabled` Bool,
    `dashboard_show_ticketID` UInt16,
    `online_deposit_enabled` Bool,
    `bets_cancel_window_after_match` Int32,
    `amole_enable_option` UInt16,
    `sales_cancel_window` Int32,
    `cashback_rule` UInt16 DEFAULT 0,
    `offline_coupon_id_length` Int32,
    `offline_ticket_id_length` Int32,
    `online_ticket_id_length` Int32,
    `slip_duplicate_enabled` Bool,
    `registeration_enabled` Bool,
    `disable_main_registeration` Bool,
    `bet_slip_valid_duration` Int32,
    `basic_cashback_valid_duration` Int32 DEFAULT 0,
    `slip_computer_class` String DEFAULT '',
    `digimoney_enable_option` UInt16,
    `ebirr_enable_option` UInt16,
    `hellocash_lion_enable_option` UInt16,
    `hellocash_wegagen_enable_option` UInt16,
    `mtn_momo_enable_option` UInt16,
    `branch_payment_enable_option` UInt16,
    `show_staketax_information` Bool,
    `show_wintax_information` Bool,
    `show_branch_withdrawal_request_code` Bool,
    `sms_branch_withdrawal_request_code` Bool,
    `branch_withdrawal_trans_fee` Float64,
    `branch_withdrawal_trans_suffix` UInt16,
    `momo_withdrawal_trans_fee` Float64,
    `momo_withdrawal_trans_suffix` UInt16,
    `sms_branch_withdrawal` Bool,
    `sms_branch_deposit` Bool,
    `email` String DEFAULT '',
    `facebook` String DEFAULT '',
    `instagram` String DEFAULT '',
    `telegram` String DEFAULT '',
    `telphone` String DEFAULT '',
    `twitter` String DEFAULT '',
    `about_company` String,
    `underage_rule` String,
    `referral_award_amount` Decimal64(2),
    `referral_criteria_min_bet_amount` Decimal64(2),
    `referral_criteria_min_deposit_amount` Decimal64(2),
    `referral_type` Int32 DEFAULT 0,
    `referral_badged_commission_support` Bool,
    `transfer_enabled` Bool,
    `super_jackpot_offline_support` Bool,
    `wallet_balance_deposit_limit` Nullable(Decimal64(2)),
    `main_dash_enabled` Bool,
    `min_allowed_transfer_amount` Decimal64(2),
    `cbebirr_enable_option` UInt16,
    `send_bet_cancelled_sms_message` Bool,
    `send_bet_placed_sms_message` Bool,
    `send_deposit_succeed_sms_message` Bool,
    `send_password_reset_verification_sms_message` Bool,
    `send_phone_confirmation_sms_message` Bool,
    `send_registeration_confirmation_sms_message` Bool,
    `send_won_bet_sms_message` Bool,
    `main_sport_type_id` Int32 DEFAULT 0,
    `frontend_template` UInt16,
    `frontend_single_image` String DEFAULT '',
    `country_code` Int32,
    `domain_name` String,
    `name` String,
    `frontend_template_max_height` UInt16,
    `logo` String DEFAULT '',
    `loading_logo` String DEFAULT '',
    `show_cashback_rule` Bool,
    `underage_img` String DEFAULT '',
    `country` Int32,
    `digimoney_ecocash` UInt16,
    `digimoney_emali` UInt16,
    `digimoney_fnb` UInt16,
    `digimoney_fnb_eft` UInt16,
    `digimoney_fnb_wallet` UInt16,
    `digimoney_momo` UInt16,
    `digimoney_mpesa` UInt16,
    `digimoney_stndbank` UInt16,
    `loyality_enabled` Bool,
    `sales_current_version` Float64,
    `sales_supported_version` Float64,
    `is_language_supported` Bool,
    `print_mobile` String DEFAULT '',
    `print_telphone` String DEFAULT '',
    `print_underage_rule` String,
    `company_moto` String DEFAULT '',
    `tiktok` String DEFAULT '',
    `hot_now_label` String,
    `telebirr_enable_option` UInt16,
    `registeration_conf_required` Bool,
    `print_code_type` UInt64 DEFAULT 0,
    `print_sub_moto` String DEFAULT '',
    `digicard_enable_option` UInt16,
    `language_code` String,
    `digimoney_ned_bank` UInt16,
    `show_virtual_games` Bool,
    `kiron_style` String,
    `sales_max_allowed_daily_cancel_count` Int32,
    `sales_max_allowed_daily_cancel_volume` Int32,
    `sales_max_allowed_stake_cancel` Float64,
    `kiron_operator_id` Int32,
    `landingpage_match_list_type` UInt64,
    `cbebirr_shortcode` String,
    `contact_number` Int32,
    `branch_maximum_daily_withdraw` Float64,
    `onlineagent_enable_option` UInt16,
    `cashout_rule` UInt16 DEFAULT 0,
    `enable_bet4me_bet_placed_sms` Bool,
    `branch_withdrawal_rule` UInt16,
    `sales_enable_request_withdraw` Bool,
    `chappa_enable_option` UInt16,
    `max_allowed_transfer_amount` Decimal64(2),
    `max_daily_number_transfer` Int32,
    `mobile_submenu_type` UInt16,
    `mobile_matchlist_type` UInt16,
    `mobile_fixedfooter_type` UInt16,
    `mtn_momo_deposit_otp_required` UInt64,
    `mtn_momo_withdraw_otp_required` UInt64,
    `desktop_menubar_type` UInt16,
    `mobile_menubar_type` UInt16,
    `kacha_enable_option` UInt16,
    `mpesa_enable_option` UInt16,
    `underage_limit` UInt16,
    `bot_current_version` Float64,
    `bot_supported_version` Float64,
    `santim_enable_option` UInt16,
    `instacash_enable_option` UInt16,
    `unayo_enable_option` UInt16,
    `mpesake_enable_option` UInt16,
    `app_url` String,
    `online_bet_support` Bool,
    `emali_enable_option` UInt16,
    `yo_uganda_enable_option` UInt16,
    `chapa_deposit_fee` Float64,
    `chapa_withdraw_fee` Float64,
    `santimpay_deposit_fee` Float64,
    `santimpay_withdraw_fee` Float64,
    `android_app_url` String DEFAULT '',
    `ios_app_url` String DEFAULT '',
    `unipesa_enable_option` UInt16,
    `ethio_telecom_sms_service_provider` String DEFAULT '',
    `branch_maximum_single_withdraw` Float64,
    `online_maximum_single_withdraw` Float64,
    `virtual_bet_tax_rate` Float64,
    `virtual_payout_tax_rate` Float64,
    `arifpay_enable_option` UInt16,
    `update_account_phonenumber` Bool,
    `emola_enable_option` UInt16,
    `paytota_enable_option` UInt16,
    `registeration_flow` UInt16 DEFAULT 0,
    `freshpay_enable_option` UInt16,
    `last_winner_max_payout` Float64,
    `last_winner_max_stake` Float64,
    `last_winner_min_payout` Float64,
    `last_winner_min_stake` Float64,
    `last_winner_no_of_tickets` Int32,
    `last_winner_retain_hours` Int32,
    `wallet_transfer_require_otp` Bool,
    `lenco_enable_option` UInt16,
    `alanbase_affiliate_enabled` Bool,
    `cashier_can_view_agent_balance` Bool,
    `lucky_leads_affiliate_enabled` Bool,
    `can_settlement_task_run` Bool,
    `mpesa_et_enable_option` UInt16,
    `send_prepaid_credit_message` Bool,
    `send_prepaid_deposit_message` Bool,
    `send_prepaid_withdraw_message` Bool,
    `min_agent_balance_threshold` Decimal64(2),
    `pos_login_otp_required` Bool,
    `fenanpay_enable_option` UInt16,
    `oleq_enable_option` UInt16,
    `top_winners_data_limit` Int32,
    `_version` UInt64 DEFAULT 0,
    `_is_deleted` UInt8 DEFAULT 0,
    `_extracted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_version, _is_deleted)
ORDER BY (`configuration_ptr_id`)
SETTINGS clean_deleted_rows = 'Always',
         index_granularity = 8192;
