CREATE TABLE IF NOT EXISTS analytics.`flatodd_mainconfiguration`
(
    `cashback_rule` String,
    `dashboard_show_ticketID` String,
    `branch_withdrawal_trans_suffix` String,
    `momo_withdrawal_trans_suffix` String,
    `cbebirr_enable_option` String,
    `frontend_template` String,
    `frontend_template_max_height` String,
    `digimoney_ecocash` String,
    `digimoney_emali` String,
    `digimoney_fnb` String,
    `digimoney_fnb_eft` String,
    `digimoney_fnb_wallet` String,
    `amole_enable_option` String,
    `digimoney_momo` String,
    `digimoney_mpesa` String,
    `digimoney_stndbank` String,
    `telebirr_enable_option` String,
    `print_code_type` String,
    `digicard_enable_option` String,
    `digimoney_ned_bank` String,
    `landingpage_match_list_type` String,
    `onlineagent_enable_option` String,
    `cashout_rule` String,
    `branch_withdrawal_rule` String,
    `chappa_enable_option` String,
    `mobile_submenu_type` String,
    `mobile_matchlist_type` String,
    `mobile_fixedfooter_type` String,
    `mtn_momo_deposit_otp_required` String,
    `mtn_momo_withdraw_otp_required` String,
    `desktop_menubar_type` String,
    `mobile_menubar_type` String,
    `digimoney_enable_option` String,
    `kacha_enable_option` String,
    `mpesa_enable_option` String,
    `underage_limit` String,
    `santim_enable_option` String,
    `instacash_enable_option` String,
    `unayo_enable_option` String,
    `mpesake_enable_option` String,
    `emali_enable_option` String,
    `yo_uganda_enable_option` String,
    `unipesa_enable_option` String,
    `ebirr_enable_option` String,
    `arifpay_enable_option` String,
    `emola_enable_option` String,
    `paytota_enable_option` String,
    `registeration_flow` String,
    `freshpay_enable_option` String,
    `lenco_enable_option` String,
    `mpesa_et_enable_option` String,
    `fenanpay_enable_option` String,
    `oleq_enable_option` String,
    `hellocash_lion_enable_option` String,
    `hellocash_wegagen_enable_option` String,
    `mtn_momo_enable_option` String,
    `branch_payment_enable_option` String,
    `_version` UInt64 DEFAULT 0,
    `_is_deleted` UInt8 DEFAULT 0,
    `_extracted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY tuple()
SETTINGS index_granularity = 8192;
