CREATE TABLE IF NOT EXISTS analytics.`mpesa_ke_depositpaymentrequest`
(
    `id` Int64,
    `transaction_reference` String,
    `transaction_type` LowCardinality(String),
    `transaction_id` Int32,
    `transaction_time` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `business_short_code` String,
    `bill_ref_number` Int32,
    `invoice_number` Int32,
    `org_account_balance` Int32,
    `third_party_trans_id` Int32,
    `msisdn` String,
    `first_name` String,
    `middle_name` String,
    `last_name` String,
    `user_identifier` Int32,
    `comment` String,
    `amount` Decimal64(2),
    `status` UInt16,
    `committed_at` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `created_at` DateTime64(6, 'UTC'),
    `updated_at` DateTime64(6, 'UTC'),
    `bank_transaction_id` Int32,
    `user_id` Int32,
    `deposit_type` LowCardinality(String),
    `account_reference` Int32,
    `checkout_request_id` Int32,
    `merchant_request_id` Int32,
    `phone_number` Int32,
    `receipt_number` Int32,
    `response_code` String,
    `response_description` String,
    `result_code` Int32 DEFAULT 0,
    `result_description` String,
    `transaction_date` DateTime64(6, 'UTC') DEFAULT toDateTime(0),
    `_version` UInt64 DEFAULT 0,
    `_is_deleted` UInt8 DEFAULT 0,
    `_extracted_at` DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(_version, _is_deleted)
ORDER BY (`id`)
PARTITION BY toYYYYMM(`created_at`)
SETTINGS clean_deleted_rows = 'Always',
         index_granularity = 8192;
